### ISSUE TITLE
[BUG]: Crash 

### ISSUE THREAD

**Issue by SrYthan** [Thorfusion/Mekanism-Community-Edition#104]
### Describe the bug

When Go out de chunk, crash

### Expected behavior

I think itd abaut chunk unload

### Mekanism Version

9.10.26

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Linux

### The crash report in folder ./crash-reports (both server and client logs)

```shell
Time: 3/19/23 2:31 PM
Description: Exception while updating neighbours

java.lang.NullPointerException: Exception while updating neighbours
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:39)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.loopThrough(UpdateProtocol.java:232)
	at mekanism.common.multiblock.UpdateProtocol.doUpdate(UpdateProtocol.java:439)
	at mekanism.common.tile.TileEntityMultiblock.update(TileEntityMultiblock.java:142)
	at mekanism.common.tile.TileEntityStructuralGlass.update(TileEntityStructuralGlass.java:41)
	at mekanism.common.block.BlockBasic.func_149695_a(BlockBasic.java:164)
	at net.minecraft.world.World.func_147460_e(World.java:1127)
	at aroma1997.uncomplication.enet.EnergyNetLocal.update(EnergyNetLocal.java:616)
	at aroma1997.uncomplication.enet.EnergyNetLocal.removeTileEntity(EnergyNetLocal.java:95)
	at aroma1997.uncomplication.enet.EnergyNetLocal.removeTile(EnergyNetLocal.java:85)
	at aroma1997.uncomplication.enet.EventHandler.onEnergyTileUnload(EventHandler.java:37)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_674_EventHandler_onEnergyTileUnload_EnergyTileUnloadEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:149)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.deregister(TileEntityTurbineValve.java:133)
	at mekanism.generators.common.tile.turbine.TileEntityTurbineValve.onChunkUnload(TileEntityTurbineValve.java:160)
	at net.minecraft.world.World.func_72939_s(World.java:2515)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by maggi373** [comment]
closing issue due to missing information, the form is very clear and not following it is auto close of issue
