### ISSUE TITLE
[BUG?] [1.12.2]: Industrial Upgrade rejecting Mekanism due to some API change?

### ISSUE THREAD

**Issue by aking4125** [Thorfusion/Mekanism-Community-Edition#119]
### Describe the bug

Hello,

As of [Industrial Upgrade](https://github.com/ZelGimi/industrialupgrade) update 2.5.0.10, the mod rejects Mekanism and causes the game to crash with the following report: 

[crash-2023-05-22_11.09.04-client.txt](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11532982/crash-2023-05-22_11.09.04-client.txt)

Specifically this line here should be of interest: 

`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Upgrade (industrialupgrade)
Caused by: java.lang.Exception: The author of the Mekanism mod fix your api! Your api breaks the launch of my mod with yours!`

[debug.log](https://github.com/Thorfusion/Mekanism-Community-Edition/files/11532979/debug.log)

On the [curseforge](https://www.curseforge.com/minecraft/mc-mods/industrial-upgrade/files/4546182) and [modrinth](https://modrinth.com/mod/industrialupgrade/version/2.5.0.10) page for the download, the number 3 on the changelog states `Completely reject Mekanism`

Any update prior to 2.5.0.10 works and allows the game to boot with Mekanism. Though, in our server, we haven't directly experienced any issues with Industrial Upgrade and Mekanism together in our builds for a few months now so I'm not entirely sure what is going on. Just simply reporting this as a "heads up".

### To Reproduce

1. Install the latest version of Forge for 1.12.2
2. Install Industrial Upgrade update 2.5.0.10
3. Install the current latest version IndustrialCraft 2 (Required by Industrial Upgrade)
4. Install the current latest version of Mekanism Community Edition which is currently `CE 9.12.5` or the original Mekanism mod (which is no longer supported on 1.12.2 hence why I am here)
5. Game crashes with the above report

### Expected behavior

Uhh I guess for both to work but it seems the mod author of Industrial Upgrade is self rejecting Mekansim entirely.

### Mekanism Version

Mekanism CE 9.12.5 CORE

### Minecraft Version is this regarding?

1.12.2

### What OS are you seeing the problem on?

Windows

### Name of modpack if applicable

None

### Version of said modpack if applicable

None

### The crash report in folder ./crash-reports (both server and client logs)

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-Community-Edition-1.12.2-9.12.5-Core.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/22/23 11:09 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Industrial Upgrade (industrialupgrade)
Caused by: java.lang.Exception: The author of the Mekanism mod fix your api! Your api breaks the launch of my mod with yours!
	at com.denfop.IUCore.load(IUCore.java:359)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_372, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 8899786888 bytes (8487 MB) / 9646243840 bytes (9199 MB) up to 9646243840 bytes (9199 MB)
	JVM Flags: 25 total; -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=2 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms9216m -Xmx9216m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version       | Source                                            | Signature                                |
	|:----- |:----------------- |:------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2        | minecraft.jar                                     | None                                     |
	| LCH   | mcp               | 9.42          | minecraft.jar                                     | None                                     |
	| LCH   | FML               | 8.0.99.99     | forge-1.12.2-14.23.5.2860-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2860  | forge-1.12.2-14.23.5.2860-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ic2               | 2.8.221-ex112 | industrialcraft-2-2.8.221-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | mekanism          | 9.12.5        | Mekanism-Community-Edition-1.12.2-9.12.5-Core.jar | None                                     |
	| LCE   | industrialupgrade | 2.5.0.10      | IndustrialUpgrade-1.12.2-2.5.0.10.jar             | None                                     |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-Community-Edition-1.12.2-9.12.5-Core.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 531.79' Renderer: 'NVIDIA GeForce GTX 1070/PCIe/SSE2'
```

**Comment by maggi373** [comment]
he released a new update removing this feature, however we are open to fix any issues. i tried to compile 2.5.0.10 and it didnt find all the deps. so i wont investigate further.
