### ISSUE TITLE
[BUG]: Crash when opening turbine statistics

### ISSUE THREAD

**Issue by YukiLucky** [Thorfusion/Mekanism-Community-Edition#172]
### Describe the bug

While using Mekanism:CE with Better Fusion Reactor, opening turbine statistics tab makes the game, or server, to crash.

### To Reproduce

1. Construct a turbine of any size
2. Click on 'Statistics'
3. Get crash

### Expected behavior

Display statistics tab without crashing.

### Mekanism Version

9.12.8

### Minecraft Version is this regarding?

1.12.2

### What OS are you seeing the problem on?

Windows

### The crash report in folder ./crash-reports (both server and client logs)

```shell
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MekanismCoremod (Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 4/23/24 2:24 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:324)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 152
	Entity Name: Yuki_Luckyy
	Entity's Exact location: 926.70, 4.00, 391.07
	Entity's Block location: World: (926,4,391), Chunk: (at 14,0,7 in 57,24; contains blocks 912,0,384 to 927,255,399), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:642)
	at net.minecraft.world.World.func_72939_s(World.java:1737)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['Yuki_Luckyy'/152, l='New World', x=926.70, y=4.00, z=391.07]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4231920455192726023
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,2*minecraft:dirt,minecraft:grass;1;village
	Level spawn location: World: (926,4,379), Chunk: (at 14,0,11 in 57,23; contains blocks 912,0,368 to 927,255,383), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Level time: 13851 game time, 13851 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 109204 (now: false), thunder time: 1060 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1181148840 bytes (1126 MB) / 1695023104 bytes (1616 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                                                  | Signature                                |
	|:------ |:------------------ |:------------ |:------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                                           | None                                     |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                                           | None                                     |
	| LCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | mekanism           | 9.12.8       | Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar       | None                                     |
	| LCHIJA | mekanismgenerators | 9.12.8       | Mekanism-Community-Edition-1.12.2-9.12.8-Generators.jar | None                                     |
	| LCHIJA | bfr                | 1.0.5        | BetterFusionReactor-1.12.2-1.0.7.jar                    | None                                     |
	| LCHIJA | mekanismtools      | 9.12.8       | Mekanism-Community-Edition-1.12.2-9.12.8-Tools.jar      | None                                     |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-Community-Edition-1.12.2-9.12.8-Core.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Yuki_Luckyy'/152, l='New World', x=926.70, y=4.00, z=391.07]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by maggi373** [comment]
have you tried to update java, as youre running quite old version. and have you tried vanilla mek to check if the issue is ours or not?

**Comment by maggi373** [comment]
fixed in #256
