### ISSUE TITLE
[BUG]: Game crashes when openening Creative Inventroy Tab "Tools" or "Mekanism"

### ISSUE THREAD

**Issue by jolesh** [Thorfusion/Mekanism-Community-Edition#197]
### Describe the bug

The games crashes when opening the Creative Inventroy Tab "Tools" or "Mekanism". Propably because it can't find one of the items located there. In the Mekanism tháb it only crashes when scroling almost all the way down.

I originally found this bug, because my world crashed when I died and keep crashing when reloading. I found this error message:
`[Client thread/ERROR] Failed to find identifier for: net.minecraft.item.ItemBlock@111f87f4` With changing ids in the end for every crash.

I found this bug with other mods installed, but is still accours without all other mods also without the MEK:CE Modules

Edit: I now tried switching to the non-CE version and the same error still occours.

### To Reproduce

1. Start world with mekanism
2. Open Creative Inventory
3. Select the Tools Tab or the "MEkanism" Tab and scroll all the way down

### Expected behavior

Show Creative Inventory Tab

### Mekanism Version

Mekanism CE 9.10.37 CORE, Mekanism CE 9.10.41 CORE, Mekanism CE 9.10.26 CORE (I tried the newest oldest and one in the middle and they are all crashing)

### Minecraft Version is this regarding?

1.7.10

### What OS are you seeing the problem on?

Windows

### The crash report in folder ./crash-reports (both server and client logs)

```shell
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/6/24 1:27 PM
Description: Rendering item

java.lang.IncompatibleClassChangeError: Expected static field codechicken.lib.render.CCRenderState.useNormals
	at codechicken.microblock.ItemSawRenderer$.renderItem(ItemSaw.scala:86)
	at codechicken.microblock.ItemSawRenderer$.renderItem(ItemSaw.scala:63)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:271)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.microblock.ItemSawRenderer$.renderItem(ItemSaw.scala:86)
	at codechicken.microblock.ItemSawRenderer$.renderItem(ItemSaw.scala:63)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

-- Item being rendered --
Details:
	Item Type: codechicken.microblock.ItemSaw@1fb6a13a
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:271)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (161, 201). Absolute: (322, 76)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['jolesho'/91, l='MpServer', x=584.86, y=59.62, z=520.57]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (585,64,520), Chunk: (at 9,4,8 in 36,32; contains blocks 576,0,512 to 591,255,527), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Level time: 7200 game time, 7200 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 52 total; [EntityZombie['Zombie'/262, l='MpServer', x=619.50, y=37.00, z=522.50], EntityBat['Bat'/395, l='MpServer', x=594.14, y=12.00, z=468.64], EntityCreeper['Creeper'/270, l='MpServer', x=567.50, y=7.00, z=572.50], EntitySkeleton['Skeleton'/271, l='MpServer', x=571.92, y=7.00, z=571.66], EntityZombie['Zombie'/22, l='MpServer', x=508.63, y=16.00, z=538.69], EntitySkeleton['Skeleton'/23, l='MpServer', x=507.50, y=18.00, z=530.91], EntitySkeleton['Skeleton'/24, l='MpServer', x=507.34, y=17.00, z=537.78], EntityBat['Bat'/25, l='MpServer', x=506.50, y=14.00, z=536.25], EntityEnderman['Enderman'/27, l='MpServer', x=507.31, y=14.99, z=568.35], EntityZombie['Zombie'/30, l='MpServer', x=513.50, y=30.00, z=445.50], EntityBabySkeleton['Baby Skeleton'/31, l='MpServer', x=519.63, y=18.00, z=491.59], EntityCreeper['Creeper'/32, l='MpServer', x=524.50, y=19.00, z=489.50], EntityBat['Bat'/33, l='MpServer', x=517.34, y=19.64, z=507.34], EntityZombie['Zombie'/34, l='MpServer', x=518.50, y=13.00, z=520.50], EntityBabySkeleton['Baby Skeleton'/35, l='MpServer', x=525.50, y=12.00, z=550.47], EntitySkeleton['Skeleton'/36, l='MpServer', x=529.50, y=19.00, z=486.06], EntitySkeleton['Skeleton'/37, l='MpServer', x=528.41, y=18.00, z=480.88], EntityCreeper['Creeper'/42, l='MpServer', x=555.41, y=12.00, z=512.00], EntitySkeleton['Skeleton'/43, l='MpServer', x=552.69, y=13.00, z=516.44], EntityZombie['Zombie'/171, l='MpServer', x=557.01, y=16.00, z=511.66], EntitySkeleton['Skeleton'/44, l='MpServer', x=552.31, y=13.00, z=513.31], EntityCreeper['Creeper'/45, l='MpServer', x=548.00, y=44.00, z=595.47], EntitySkeleton['Skeleton'/46, l='MpServer', x=574.91, y=24.00, z=508.50], EntityBat['Bat'/47, l='MpServer', x=579.94, y=26.98, z=493.72], EntityBat['Bat'/49, l='MpServer', x=574.75, y=39.39, z=482.84], EntityBat['Bat'/50, l='MpServer', x=582.31, y=26.74, z=500.44], EntityBat['Bat'/51, l='MpServer', x=586.66, y=33.79, z=510.28], EntityZombie['Zombie'/179, l='MpServer', x=580.50, y=9.00, z=468.50], EntityBat['Bat'/52, l='MpServer', x=585.25, y=33.10, z=514.50], EntityBat['Bat'/53, l='MpServer', x=585.38, y=36.10, z=513.47], EntityBabySkeleton['Baby Skeleton'/54, l='MpServer', x=589.50, y=21.00, z=582.50], EntityCreeper['Creeper'/55, l='MpServer', x=577.50, y=40.00, z=598.50], EntityCreeper['Creeper'/56, l='MpServer', x=577.50, y=40.00, z=596.50], EntitySkeleton['Skeleton'/58, l='MpServer', x=599.50, y=33.00, z=506.88], EntityBat['Bat'/59, l='MpServer', x=593.50, y=33.10, z=508.94], EntityCreeper['Creeper'/60, l='MpServer', x=597.03, y=30.00, z=509.50], EntityBat['Bat'/61, l='MpServer', x=602.25, y=53.10, z=502.25], EntitySkeleton['Skeleton'/62, l='MpServer', x=603.88, y=36.00, z=526.53], EntityBabySkeleton['Baby Skeleton'/63, l='MpServer', x=590.29, y=31.85, z=538.49], EntityCreeper['Creeper'/319, l='MpServer', x=506.50, y=20.00, z=491.50], EntitySkeleton['Skeleton'/64, l='MpServer', x=600.53, y=33.00, z=541.09], EntityBat['Bat'/65, l='MpServer', x=595.44, y=35.10, z=529.25], EntityBabySkeleton['Baby Skeleton'/66, l='MpServer', x=596.41, y=22.00, z=575.88], EntityBat['Bat'/68, l='MpServer', x=623.38, y=52.26, z=489.06], EntitySkeleton['Skeleton'/69, l='MpServer', x=616.50, y=55.00, z=489.50], EntityCreeper['Creeper'/70, l='MpServer', x=613.28, y=52.00, z=496.75], EntitySkeleton['Skeleton'/71, l='MpServer', x=611.47, y=40.00, z=520.94], EntityCreeper['Creeper'/335, l='MpServer', x=661.50, y=42.00, z=479.50], EntitySkeleton['Skeleton'/211, l='MpServer', x=593.50, y=23.00, z=490.50], EntityClientPlayerMP['jolesho'/91, l='MpServer', x=584.86, y=59.62, z=520.57], EntityCreeper['Creeper'/240, l='MpServer', x=586.50, y=35.00, z=527.50], EntityBabySkeleton['Baby Skeleton'/254, l='MpServer', x=547.26, y=14.00, z=537.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 380949632 bytes (363 MB) / 671088640 bytes (640 MB) up to 4294967296 bytes (4096 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: none
	LaunchWrapper: 24 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 9 total; -Xmx4096M -XX:MetaspaceSize=256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 9, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	Mekanism{9.10.37} [Mekanism Community Edition] (Mekanism-Community-Edition-1.7.10-9.10.37-Core.jar) 
	UCHIJAAAA	MekanismGenerators{9.10.41} [MekanismGenerators Community Edition] (Mekanism-Community-Edition-1.7.10-9.10.41-Generators.jar) 
	UCHIJAAAA	MekanismTools{9.10.41} [MekanismTools Community Edition] (Mekanism-Community-Edition-1.7.10-9.10.41-Tools.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.0.8.16} [MrTJPCore] (MrTJPCore-1.7.10-1.0.8.16-universal.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 23.19.12.02.240618' Renderer: 'AMD Radeon(TM) Graphics'
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) Graphics GL version 4.6.0 Compatibility Profile Context 23.19.12.02.240618, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

### Please provide the following other files

[2024-12-06-7.log](https://github.com/user-attachments/files/18038084/2024-12-06-7.log)

**Comment by jolesh** [comment]
Nevermind, me stupid. I had to use "CodeChickenLib-1.7.10-1.1.3.141-universal" instead of "CodeChickenLib-1.3.0.jar"
