### ISSUE TITLE
[BUG] crash with Quantum Entangloporter

### ISSUE THREAD

**Issue by SrYthan** [Thorfusion/Mekanism-Community-Edition#68]
**Crash**
When i set frequence in the Quantum entangloport this cause a crash.

**To Reproduce**

1. Place a Quantum entangloport 
2. Open and set a frequence

**Desktop (please complete the following information):**
 - OS: Win 10
 - Mekanism Version: latest

Crash reports

java.lang.NullPointerException
    at mekanism.client.gui.GuiQuantumEntangloporter.setFrequency(GuiQuantumEntangloporter.java:116)
    at mekanism.client.gui.GuiQuantumEntangloporter.func_73864_a(GuiQuantumEntangloporter.java:235)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by maggi373** [comment]
Please fix your bug report as its incomplete and not following the guide.

**Comment by SrYthan** [comment]
sorry, i make this in my cell phone, i just copied the error part because its more simple and fast to me.

**Comment by SrYthan** [comment]
[crash-23-12-2022_03.50.15-client.txt](https://github.com/Thorfusion/Mekanism-1.7.10-Community-Edition/files/10296420/crash-23-12-2022_03.50.15-client.txt)

**Comment by maggi373** [comment]
it's already been fixed :) , testing the changes as of now
